version: '2'

services:
  subsonic:

    build: .
    container_name: subsonic
    restart: always
    privileged: true

    volumes:
      - /volume1/docker/supysonic:/var/lib/supysonic
      
      # Update to reflect the path to your media...
      - /volume1/music/iTunes/iTunes_Media/Music:/media

    ports:
      - 5080:5000

    environment:
      - SUPYSONIC_RUN_MODE=standalone

    cpu_shares: 1024
